<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Pruebas unitarias y de integración de Delosi.InvoicingInvoices</Description>
    <RootNamespace>Delosi.InvoicingInvoices.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Delosi.InvoicingInvoices.Api\Delosi.InvoicingInvoices.Api.csproj" />
    <ProjectReference Include="..\..\src\Delosi.InvoicingInvoices.Application\Delosi.InvoicingInvoices.Application.csproj" />
    <ProjectReference Include="..\..\src\Delosi.InvoicingInvoices.Domain\Delosi.InvoicingInvoices.Domain.csproj" />
    <ProjectReference Include="..\..\src\Delosi.InvoicingInvoices.Infrastructure\Delosi.InvoicingInvoices.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="6.*" />
    <PackageReference Include="NSubstitute" Version="5.*" />
    <PackageReference Include="coverlet.collector" Version="6.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
