-- =============================================================================
-- invoicing_db — Creación de tablas del dominio FACTURAS
-- Motor: PostgreSQL 15+ (Amazon Aurora PostgreSQL-Compatible)
--
-- CONTENIDO: 4 tablas, una por cada tabla del diagrama FACTURAS.
--
--   invoice             FACTURA
--   invoice_detail      FACTURA_DETALLE
--   invoice_tax         FACTURA_IMPUESTO
--   invoice_integration FACTURA_INTEGRACION_SAP
-- =============================================================================

begin;

create or replace function fn_set_modified_at()
returns trigger
language plpgsql
as $$
begin
    new.modified_at := now();
    return new;
end;
$$;

comment on function fn_set_modified_at() is
    'Trigger BEFORE UPDATE: sella modified_at con la hora del servidor.';


-- -----------------------------------------------------------------------------
-- invoice — FACTURA
-- -----------------------------------------------------------------------------
create table invoice
(
    invoice_id               bigint generated by default as identity -- id_factura
        constraint pk_invoice primary key,
    company_id               bigint        not null,                 -- id_sociedad
    customer_id              bigint        not null,                 -- id_cliente
    document_type_id         bigint        not null,                 -- id_tipo_documento
    sales_organization_id    bigint        not null,                 -- id_organizacion_venta
    distribution_channel_id  bigint        not null,                 -- id_canal_distribucion
    payment_term_id          bigint        not null,                 -- id_condicion_pago
    payment_type_id          bigint        not null,                 -- id_tipo_pago
    brand_id                 bigint        not null,                 -- id_marca
    brand_code               varchar(6)    not null,
    store_id                 bigint,                                 -- id_tienda
    store_code               varchar(6),
    customer_document_number varchar(15)   not null,
    customer_legal_name      varchar(200)  not null,
    series                   varchar(4)    not null,                 -- serie
    invoice_number           varchar(8)    not null,                 -- numero
    issue_date               date          not null,                 -- fecha_emision
    due_date                 date,
    currency                 char(3)       not null default 'PEN',   -- moneda
    exchange_rate            numeric(12,6) not null default 1,
    subtotal                 numeric(18,2) not null default 0,       -- subtotal
    discount                 numeric(18,2) not null default 0,       -- descuento_total
    service_charge_total     numeric(18,2) not null default 0,       -- recargo_consumo_total
    tax_total                numeric(18,2) not null default 0,       -- igv_total
    total                    numeric(18,2) not null default 0,       -- total
    status                   varchar(20)   not null default 'REGISTERED', -- estado
    created_by               varchar(50),                            -- creado_por
    created_at               timestamp     not null default now(),   -- fecha_creacion
    modified_by              varchar(50),                            -- modificado_por
    modified_at              timestamp,                              -- fecha_modificacion

    constraint uq_invoice_document unique (company_id, document_type_id, series, invoice_number),
    constraint ck_invoice_status   check (status in ('REGISTERED', 'ISSUED', 'SENT', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
    constraint ck_invoice_dates    check (due_date is null or due_date >= issue_date),
    constraint ck_invoice_rate     check (exchange_rate > 0),
    constraint ck_invoice_amounts  check (
        subtotal >= 0 and discount >= 0 and service_charge_total >= 0
        and tax_total >= 0 and total >= 0
    ),
    constraint ck_invoice_total    check (
        abs(total - (subtotal - discount + service_charge_total + tax_total)) <= 0.01
    )
);

comment on table  invoice                          is 'Cabecera de las facturas de ventas corporativas. Equivale a FACTURA.';
comment on column invoice.invoice_number           is 'Correlativo del comprobante.';
comment on column invoice.sales_organization_id    is 'Organización de ventas SAP.';
comment on column invoice.brand_code               is 'Código de marca copiado del maestro al emitir.';
comment on column invoice.store_code               is 'Código de tienda copiado del maestro al emitir.';
comment on column invoice.customer_document_number is 'RUC/documento del cliente.';
comment on column invoice.customer_legal_name      is 'Razón social del cliente.';
comment on column invoice.exchange_rate            is 'Tipo de cambio a la moneda funcional de la sociedad.';
comment on column invoice.status                   is 'REGISTERED -> ISSUED -> SENT -> ACCEPTED | REJECTED. CANCELLED es terminal.';

create index ix_invoice_customer_date
    on invoice (customer_id, issue_date desc);

create index ix_invoice_company_date
    on invoice (company_id, issue_date desc);

create index ix_invoice_brand_date
    on invoice (brand_id, issue_date desc);

create index ix_invoice_store_date
    on invoice (store_id, issue_date desc) where store_id is not null;

-- Cola operativa: facturas pendientes de enviar o rechazadas.
create index ix_invoice_pending
    on invoice (status, issue_date)
    where status in ('REGISTERED', 'ISSUED', 'REJECTED');

create trigger trg_invoice_modified_at
    before update on invoice
    for each row execute function fn_set_modified_at();


-- -----------------------------------------------------------------------------
-- invoice_detail — FACTURA_DETALLE
-- -----------------------------------------------------------------------------
create table invoice_detail
(
    invoice_detail_id     bigint generated by default as identity -- id_factura_detalle
        constraint pk_invoice_detail primary key,
    invoice_id            bigint        not null,                 -- id_factura
    line_number           integer       not null,                 -- numero_linea
    concept_id            bigint        not null,                 -- id_concepto
    concept_code          varchar(20)   not null,
    material_id           bigint        not null,                 -- id_material
    material_code         varchar(20)   not null,
    accounting_account_id bigint,
    description           varchar(250)  not null,                 -- descripcion
    quantity              numeric(14,4) not null,                 -- cantidad
    unit_price            numeric(18,6) not null,                 -- precio_unitario
    discount              numeric(18,2) not null default 0,       -- descuento
    subtotal              numeric(18,2) not null default 0,       -- subtotal
    service_charge        numeric(18,2) not null default 0,       -- recargo_consumo
    tax_amount            numeric(18,2) not null default 0,       -- igv
    total                 numeric(18,2) not null default 0,       -- total

    constraint uq_invoice_detail_line    unique (invoice_id, line_number),
    constraint ck_invoice_detail_qty     check (quantity > 0),
    constraint ck_invoice_detail_line    check (line_number > 0),
    constraint ck_invoice_detail_amounts check (
        unit_price >= 0 and discount >= 0 and subtotal >= 0
        and service_charge >= 0 and tax_amount >= 0 and total >= 0
    )
);

comment on table  invoice_detail               is 'Líneas de la factura. Equivale a FACTURA_DETALLE.';
comment on column invoice_detail.unit_price    is 'Precio unitario con seis decimales.';
comment on column invoice_detail.concept_code  is 'Código de concepto. Viaja en el payload a SAP.';
comment on column invoice_detail.material_code is 'Código de material. Viaja en el payload a SAP.';

create index ix_invoice_detail_concept
    on invoice_detail (concept_id);

create index ix_invoice_detail_material
    on invoice_detail (material_id);

create index ix_invoice_detail_account
    on invoice_detail (accounting_account_id) where accounting_account_id is not null;


-- -----------------------------------------------------------------------------
-- invoice_tax — FACTURA_IMPUESTO
-- -----------------------------------------------------------------------------
create table invoice_tax
(
    invoice_tax_id    bigint generated by default as identity -- id_factura_impuesto
        constraint pk_invoice_tax primary key,
    invoice_id        bigint        not null,                 -- id_factura
    invoice_detail_id bigint,                                 -- id_factura_detalle
    tax_type          varchar(20)   not null,                 -- tipo_impuesto
    tax_code          varchar(10)   not null,                 -- codigo_impuesto
    rate              numeric(7,4)  not null,                 -- porcentaje
    taxable_base      numeric(18,2) not null,                 -- base_imponible
    amount            numeric(18,2) not null,                 -- importe

    constraint ck_invoice_tax_type check (tax_type in ('IGV', 'ISC', 'DETRACTION', 'SERVICE_CHARGE', 'OTHER')),
    constraint ck_invoice_tax_rate check (rate >= 0 and rate <= 100),
    constraint ck_invoice_tax_base check (taxable_base >= 0 and amount >= 0)
);

comment on table  invoice_tax                   is 'Impuestos y recargos de la factura o de una de sus líneas. Equivale a FACTURA_IMPUESTO.';
comment on column invoice_tax.invoice_detail_id is 'NULL = impuesto de cabecera. Con valor, debe ser una línea de ESTA factura; lo verifica el servicio.';
comment on column invoice_tax.tax_code          is 'Código tributario SUNAT (catálogo 05): 1000 IGV, 9999 otros.';

create index ix_invoice_tax_invoice
    on invoice_tax (invoice_id);

create index ix_invoice_tax_detail
    on invoice_tax (invoice_detail_id) where invoice_detail_id is not null;


-- -----------------------------------------------------------------------------
-- invoice_integration — FACTURA_INTEGRACION_SAP
-- -----------------------------------------------------------------------------
create table invoice_integration
(
    invoice_integration_id bigint generated by default as identity -- id_factura_integracion
        constraint pk_invoice_integration primary key,
    invoice_id             bigint      not null,                    -- id_factura
    target_system          varchar(20) not null,                    -- sistema_destino
    operation_type         varchar(20) not null,                    -- tipo_operacion
    request_id             varchar(64) not null,                    -- request_id
    correlation_id         varchar(64),                             -- correlation_id
    status                 varchar(20) not null default 'PENDING',  -- estado
    attempts               integer     not null default 0,          -- numero_intento
    sent_at                timestamp,                               -- fecha_envio
    responded_at           timestamp,                               -- fecha_respuesta
    response_code          varchar(20),                             -- codigo_respuesta
    response_message       varchar(1000),                           -- mensaje_respuesta
    request_payload        jsonb,
    response_payload       jsonb,
    created_at             timestamp   not null default now(),

    constraint uq_invoice_integration_request  unique (request_id),
    constraint ck_invoice_integration_op       check (operation_type in ('CREATE', 'UPDATE', 'CANCEL')),
    constraint ck_invoice_integration_status   check (status in ('PENDING', 'SENT', 'SUCCESS', 'FAILED', 'RETRYING')),
    constraint ck_invoice_integration_attempts check (attempts >= 0),
    constraint ck_invoice_integration_times    check (responded_at is null or sent_at is not null)
);

comment on table  invoice_integration                is 'Bitácora de envíos de la factura a SAP PI / SAP. Una fila por intento. Equivale a FACTURA_INTEGRACION_SAP.';
comment on column invoice_integration.target_system  is 'Sistema destino: SAP, SAP_PI.';
comment on column invoice_integration.request_id     is 'Identificador único del envío; el destino lo usa para descartar duplicados.';
comment on column invoice_integration.correlation_id is 'Correlación end-to-end con el log de la API.';

create index ix_invoice_integration_invoice
    on invoice_integration (invoice_id, created_at desc);

-- Índice parcial para el worker de reintentos: solo indexa lo pendiente.
create index ix_invoice_integration_queue
    on invoice_integration (status, created_at)
    where status in ('PENDING', 'RETRYING', 'FAILED');

create index ix_invoice_integration_correlation
    on invoice_integration (correlation_id) where correlation_id is not null;


commit;
